### PR TITLE
Added sync to node benchmark

### PR DESCRIPTION
**Pull request by m910q**

### CODE REVIEW

**Comment by aotenko** [comment]
I think this kinda defeats the purpose, but I'll merge nonetheless - it still keeps the async code in there.

**Comment by m910q** [comment]
I understand. But it's also nice to see how much is caused by the language, and how much the Promise implementation slow down things.
I did it to see the difference. And since the sync/async was both implemented in c#, I chose to commit it.

**Comment by aotenko** [comment]
Yes, I saw the figures and got it :-) makes sense.

**Comment by m910q** [comment]
Have you tried to just use the native Promise implementation instead?
I might try it when I get home.

**Comment by aotenko** [comment]
I think the original implementor tried it - see the commented out Promise.resolve(num). It seems to have a similar memory footprint problem.

**Pull request merged**
